version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:16"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user